/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
*/

#include <Arduino.h>
#include <tcMenu.h>
#include "ProjectI2c_menu.h"

// Global variable declarations

const PROGMEM ConnectorLocalInfo applicationInfo = { "FruitScreen", "e11790b2-d1bd-452a-94fd-425d4b909359" };
U8g2GfxMenuConfig gfxConfig;
U8g2MenuRenderer renderer;
U8G2_SH1106_128X64_NONAME_F_HW_I2C Config(U8G2_R0, U8X8_PIN_NONE);
// Global Menu Item declarations

const FloatMenuInfo PROGMEM minfoBatteryLevel = { "Battery Level", 6, 0xFFFF, 2, NO_CALLBACK };
FloatMenuItem menuBatteryLevel(&minfoBatteryLevel, NULL);
const AnyMenuInfo PROGMEM minfoOFFLINEMODEGetData = { "GetData", 13, 0xFFFF, 0, NO_CALLBACK };
ActionMenuItem menuOFFLINEMODEGetData(&minfoOFFLINEMODEGetData, NULL);
const SubMenuInfo PROGMEM minfoOFFLINEMODE = { "OFFLINE MODE", 2, 0xFFFF, 0, NO_CALLBACK };
RENDERING_CALLBACK_NAME_INVOKE(fnOFFLINEMODERtCall, backSubItemRenderFn, "OFFLINE MODE", -1, NO_CALLBACK)
BackMenuItem menuBackOFFLINEMODE(fnOFFLINEMODERtCall, &menuOFFLINEMODEGetData);
SubMenuItem menuOFFLINEMODE(&minfoOFFLINEMODE, &menuBackOFFLINEMODE, &menuBatteryLevel);
const AnyMenuInfo PROGMEM minfoONLINEMODESettingsFirebase = { "Firebase", 10, 0xFFFF, 0, Captiveportal };
ActionMenuItem menuONLINEMODESettingsFirebase(&minfoONLINEMODESettingsFirebase, NULL);
const AnyMenuInfo PROGMEM minfoONLINEMODESettingsWifiConnection = { "Wifi connection", 9, 0xFFFF, 0, NO_CALLBACK };
ActionMenuItem menuONLINEMODESettingsWifiConnection(&minfoONLINEMODESettingsWifiConnection, &menuONLINEMODESettingsFirebase);
const SubMenuInfo PROGMEM minfoONLINEMODESettings = { "Settings", 7, 0xFFFF, 0, NO_CALLBACK };
RENDERING_CALLBACK_NAME_INVOKE(fnONLINEMODESettingsRtCall, backSubItemRenderFn, "Settings", -1, NO_CALLBACK)
BackMenuItem menuBackONLINEMODESettings(fnONLINEMODESettingsRtCall, &menuONLINEMODESettingsWifiConnection);
SubMenuItem menuONLINEMODESettings(&minfoONLINEMODESettings, &menuBackONLINEMODESettings, NULL);
RENDERING_CALLBACK_NAME_INVOKE(fnONLINEMODEFirebaseNameRtCall, textItemRenderFn, "Firebase_Name ", 2, NO_CALLBACK)
TextMenuItem menuONLINEMODEFirebaseName(fnONLINEMODEFirebaseNameRtCall, 8, 20, &menuONLINEMODESettings);
const AnyMenuInfo PROGMEM minfoONLINEMODESpectrometerCalibrateLED = { "CalibrateLED", 12, 0xFFFF, 0, NO_CALLBACK };
ActionMenuItem menuONLINEMODESpectrometerCalibrateLED(&minfoONLINEMODESpectrometerCalibrateLED, NULL);
const AnyMenuInfo PROGMEM minfoONLINEMODESpectrometerGetData = { "GetData", 11, 0xFFFF, 0, readspectrometer };
ActionMenuItem menuONLINEMODESpectrometerGetData(&minfoONLINEMODESpectrometerGetData, &menuONLINEMODESpectrometerCalibrateLED);
const SubMenuInfo PROGMEM minfoONLINEMODESpectrometer = { "Spectrometer", 3, 0xFFFF, 0, NO_CALLBACK };
RENDERING_CALLBACK_NAME_INVOKE(fnONLINEMODESpectrometerRtCall, backSubItemRenderFn, "Spectrometer", -1, NO_CALLBACK)
BackMenuItem menuBackONLINEMODESpectrometer(fnONLINEMODESpectrometerRtCall, &menuONLINEMODESpectrometerGetData);
SubMenuItem menuONLINEMODESpectrometer(&minfoONLINEMODESpectrometer, &menuBackONLINEMODESpectrometer, &menuONLINEMODEFirebaseName);
const SubMenuInfo PROGMEM minfoONLINEMODE = { "ONLINE MODE", 1, 0xFFFF, 0, NO_CALLBACK };
RENDERING_CALLBACK_NAME_INVOKE(fnONLINEMODERtCall, backSubItemRenderFn, "ONLINE MODE", -1, NO_CALLBACK)
BackMenuItem menuBackONLINEMODE(fnONLINEMODERtCall, &menuONLINEMODESpectrometer);
SubMenuItem menuONLINEMODE(&minfoONLINEMODE, &menuBackONLINEMODE, &menuOFFLINEMODE);


// Set up code

void setupMenu() {


    prepareBasicU8x8Config(gfxConfig);
    Config.begin();
    renderer.setGraphicsDevice(&Config, &gfxConfig);
    switches.initialise(internalDigitalIo(), true);
    menuMgr.initForEncoder(&renderer, &menuONLINEMODE, 26, 25, 27);
}
